[features]
seeds = false

[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
sports_betting = "Bet1111111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"